### ISSUE TITLE
Pixi.js: Emit 'once' true does not destroy/remove the sprite/graphic from the Pixi Container.

### ISSUE THREAD

**Issue by sarahmizzi** [drawcall/Proton#70]
Using Pixi.js v 5.2.1, my Pixi Container remains littered with destroyed particles. I copy pasted [this](https://drawcall.github.io/Proton/examples/render/pixi/pixi-mulirender.html) example into my environment and it works fine.

However if I try to use `emitter.emit('once', true)`, as used in [this](https://drawcall.github.io/Proton/examples/sparks/firework/fireworks.html) example, my container does not remove the now dead particles. The particles just hang static in the canvas - as far as proton is concerned they're dead - but not removed from Pixi.

Any help please?

**Comment by jramstedt** [comment]
#55
