### ISSUE TITLE
Rotate behavior: unexpected result

### ISSUE THREAD

**Issue by kavandos** [drawcall/Proton#71]
I've tried to use particle rotation behaviour, and suddenly found unexpected results.
After digging in code I've found a Rotate method "applyBehaviour" that has 

if (this.style === 'to' || this.style === 'TO' || this.style === '_') {
    particle.rotation += particle.data.rotationB + (particle.data.rotationA - particle.data.rotationB) * this.energy
}...

It has  "+=" operator, but "=" expected here

So it's probably a bug.

**Comment by drawcall** [comment]
This is the interpolation formula. I don't know what effect you want

**Comment by kavandos** [comment]
yes I know
but if I calculate the interpolation, I usually just change rotation, but not add it to the previous one.

I suggest
particle.rotation = [interpolation]

but here I see
particle.rotation += [interpolation]

Am I wrong to suggest this behaviour?

**Comment by kavandos** [comment]
Probably I misunderstood, and Rotate means only "rotation speed". In this case everything is fine.
I just wanted a particle to start with one angle and die with another one...
