### ISSUE TITLE
Rotate is break if I use Color

### ISSUE THREAD

**Issue by kavandos** [drawcall/Proton#72]
I use rotate and it works fine
`
emitter.addBehaviour(new Proton.Rotate( new Proton.Span(0, 360), 2, "to" ));
`

but once I add Color, Rotate stops working
```

emitter.addBehaviour(new Proton.Rotate( new Proton.Span(0, 360), 2, "to" ));
emitter.addBehaviour(new Proton.Color('ff0000', 'ff0000'));

```

**Comment by kavandos** [comment]
I there a way to make it work both with Color and Rotate?

**Comment by kavandos** [comment]
P.S. CanvasRenderer

**Comment by drawcall** [comment]
I guess you use both Proton.Body and Proton.Color in CanvasRender. Oh, painting a picture in canvas is a lossy performance operation. Proton uses the canvas cache buffer for painting pictures, so this case does not support simultaneous effect. You can use webgl instead.

**Comment by drawcall** [comment]
In fact, for most practical projects you do n’t need to color a picture

**Comment by kavandos** [comment]
thanks, switched to WebGLRenderer

**Comment by kavandos** [comment]
Looks like WEBGLRenderer doesn't clear by default
