### ISSUE TITLE
Spiderweb is not interactive

### ISSUE THREAD

**Issue by Andrav90** [drawcall/Proton#73]
I've copy/pasted the proton spider web from this pen: https://codesandbox.io/s/proton-spiderweb-0fzi4.

In the pen it is interactive. but in my project not at all. Lines don't move when the cursor gets close to them, nothing happens on click.

I am using it in a React component, surrounded by a div and also after the <Particles /> tag there are some other divs.
I've tried removing the other divs but it still does not work, so I suppose the issue isn't there. Other than that, all the code is exactly as in the pen.

I am also using the same version of proton-engine and raf-manager as in the pen.

Anyone having any idea what could be causing this? 
Thank you!

**Comment by drawcall** [comment]
Please pay attention to your dom level, is it caused by a div covering the canvas or other problems
