### ISSUE TITLE
About color

### ISSUE THREAD

**Issue by king514jy** [drawcall/Proton#82]
[https://codepen.io/king514jy/pen/dyMOzMJ](https://codepen.io/king514jy/pen/dyMOzMJ)
The angle becomes invalid after adding color

**Comment by drawcall** [comment]
[https://github.com/drawcall/Proton#remarks](https://github.com/drawcall/Proton#remarks)

Use Proton.Body and Proton.Color at the same time. I suggest you'd better use the WebGLRenderer not CanvasRenderer.
