### ISSUE TITLE
WebglRenderer

### ISSUE THREAD

**Issue by Lakedaemon** [drawcall/Proton#92]
Why is it possible for my browser to look at the proton-sun example with webglrenderer
But when I try using a WebGLrenderer on my own pages, the browser complaoins that it doesn't support webgl ? 

How can I make my pages able to use webglrenderer (without enabling webgl bits in browsers) ? 

Or is there a way to blend particles with CanvaRenderer ?

**Comment by drawcall** [comment]
what system and version of browser are you using

**Comment by Lakedaemon** [comment]
Thanks for your feedback. I was answering you when I hade the idea to make another test. 

I updated my simple html page and managed to use the WebglRenderer in Chrome & Firefox (on my ubuntu box).

In fact,The Webglrender issue I'm seeing only affects the local webapp I'm writing with sveltekit & node 
So, this is not an issue with Proton which works just fine, but probably with either

I'll test in a few weeks (when I build the production app) if the issue appears on the production webapp too
node.js
sveltekit (I should update that to a newer version)
{
  npm: '7.17.0',
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}

This is a NON issue, so I'm closing it.

I wish you a good day, sir ! :)
