### ISSUE TITLE
Proton.Span is not documented anywhere

### ISSUE THREAD

**Issue by Drakim** [drawcall/Proton#99]
On the GitHub repository it is written:
> Proton.Span (or Proton.getSpan) is a very important concept of the Proton engine, it's everywhere. If you understand its usage, you can create almost any desired effect!

But nowhere does it actually explain what a Span is or what it does. I can sorta gleam from the usage that it's a range of some sort?

In the [documentation](https://projects.jpeer.at/proton/index.html#utils) the link to [Proton.Util](https://projects.jpeer.at/proton/Proton_Proton.Util.html) goes to a 404. The word "Span" does not appear in the side-menu of things to look up.

Going directly to the code at [Proton/src/math/Span.js](https://github.com/drawcall/Proton/blob/master/src/math/Span.js) does not help because the code lacks comments.

So where can I read about Span, what it does, and what I can do with it?

**Comment by drawcall** [comment]
It is a flexible range data type. Oh, its documentation has not been supplemented for the time being. can you help submit a pr

**Comment by drawcall** [comment]
Yes, check examples

**Comment by Drakim** [comment]
I don't mind submitting a pr, but I'm still extremely new to using Proton, so it will have to wait until I've grown more familiar and actually understand things properly, so I can actually explain them in writing :)
